# Generated by Django 4.1.5 on 2023-07-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractorapp', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
