# Generated by Django 4.1.5 on 2023-07-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
